# Generated by Django 4.2.7 on 2024-02-04 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationrecipient_sent_at_notificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationrecipient',
            name='status',
        ),
    ]
