app:
  name: pda
  version: 0.1.0
  cli:
    entrypoint: pda
  environment:
    prefix: PDA
    file: .env
server:
  address: 0.0.0.0
  port: 8080
  proxy_root: /
  type: django # gunicorn, uvicorn, uwsgi, django
  auto_reload: true
  workers: 3
  threads: 5
  gunicorn:
    log_level: info
    timeout: 30
  uvicorn:
    log_level: info
    keep_alive_timeout: 5
    graceful_shutdown_timeout: 5
  uwsgi:
    request_timeout: 30
db:
  engine: sqlite
  path: pda.db
#  engine: mysql
#  host: localhost
#  port: 3306
#  user: pda
#  password: pda
#  name: pda
#  engine: postgresql
#  host: localhost
#  port: 5432
#  user: pda
#  password: pda
#  name: pda
#  schema: public
cors:
  allow_credentials: true
  headers: ['*']
  methods: ['*']
  origins: ['127.0.0.1', 'localhost', 'dev.powerdnsadmin.net', '*']
csrf:
  origins: ['http://127.0.0.1', 'http://localhost', 'https://dev.powerdnsadmin.net', 'https://*.pda.powerdnsadmin.net']
web:
  name: PowerDNS Admin
  protocol: https # http, https
  host: pda.powerdnsadmin.net
  port: 443
  stopgap:
    enabled: true
    protocol: https # http, https
    domain: pda.powerdnsadmin.net
    port: 443
paths:
  root: $e{PWD}
security:
  secret_key: $e{PDA_SECRET_KEY}
email:
  from_email: no-reply@powerdnsadmin.net
  host: mail.azorian.solutions
  port: 587
  user: pda@powerdnsadmin.net
  password: A7Op53p2TsuQYmB8lxog
  ssl: false
  tls: true