services:
  app:
    container_name: pda-app
    hostname: app
    build:
        context: ../../..
        dockerfile: deploy/docker/production/Dockerfile
        args:
          - PACKAGES=build-essential,python3-dev,python3-pip,python3-venv,npm,libsasl2-dev,libldap2-dev,libssl-dev
    restart: unless-stopped
    command: pda -d app run
    volumes:
      - ../../..:/srv
    environment:
      - DEBUG=0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "0.0.0.0:8080:8080"
  static:
    container_name: pda-static
    hostname: static
    image: nginx
    restart: unless-stopped
    volumes:
      - ../../../src:/usr/share/nginx/html
    ports:
      - "0.0.0.0:8081:80"
    environment:
      - NGINX_HOST=pda.your-domain.com
      - NGINX_PORT=80
  redis:
    container_name: pda-redis
    hostname: redis
    image: redis:7
    restart: unless-stopped
    volumes:
        - redis:/data
    ports:
      - "0.0.0.0:6379:6379"
    environment:
      - REDIS_PORT=6379
  worker:
    container_name: pda-worker
    hostname: worker
    build:
      context: ../../..
      dockerfile: deploy/docker/production/Dockerfile
      args:
        - PACKAGES=build-essential,python3-dev,python3-pip,python3-venv,npm,libsasl2-dev,libldap2-dev,libssl-dev
    restart: unless-stopped
    command: python -m celery -A pda worker -l info -Q celery
    volumes:
      - ../../..:/srv
    environment:
      - DEBUG=0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  flower:
    container_name: pda-flower
    hostname: flower
    build:
      context: ../../..
      dockerfile: deploy/docker/production/Dockerfile
      args:
        - PACKAGES=build-essential,python3-dev,python3-pip,python3-venv,npm,libsasl2-dev,libldap2-dev,libssl-dev
    restart: unless-stopped
    command: python -m celery -A pda flower --port=5555 --basic-auth=pda:pda --broker-api=http://redis:6379/0
    volumes:
      - ../../..:/srv
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - worker
volumes:
  redis: