# Generated by Django 4.2.7 on 2024-02-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_invalid',
        ),
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='accountinvitation',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='accountinvitation',
            name='status',
            field=models.CharField(default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountinvitation',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
