
class Language:
    name: str
    label: str
    
    def __init__(self, name: str, label: str):
        self.name = name
        self.label = label


class Voice:
    name: str
    label: str
    language: Language
    speech_type: str
    gender: str
    
    def __init__(self, name: str, label: str, language: Language, speech_type: str, gender: str):
        self.name = name
        self.label = label
        self.language = language
        self.speech_type = speech_type
        self.gender = gender


class Say:
    """ Singleton class for managing Twilio Say verb language and voice options """

    _instance: 'Say' = None
    """ Singleton instance """

    _languages: list[Language] = []
    """ List of supported languages """

    _voices: list[Voice] = []
    """ List of supported voices """

    @property
    def languages(self) -> list[Language]:
        """ Get the list of supported languages """
        return self._languages

    @property
    def voices(self) -> list[Voice]:
        """ Get the list of supported voices """
        return self._voices

    def __init__(self):
        """ Initialize the object properties """
        self._init_languages()
        self._init_voices()

    def get_language(self, name: str) -> Language:
        """ Get a language by name """
        return next((language for language in self._languages if language.name == name), None)

    def get_language_voices(self, language: Language) -> list[Voice]:
        """ Get the list of voices for a language """
        return [voice for voice in self._voices if voice.language.name == language.name]

    def get_voice(self, name: str) -> Voice:
        """ Get a voice by name """
        return next((voice for voice in self._voices if voice.name == name), None)

    @classmethod
    def instance(cls) -> 'Say':
        """ Get the singleton instance, initializing it if necessary """
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def _init_languages(self):
        if len(self._languages):
            return

        self._languages = [
            Language(name='af-ZA', label='Afrikaans (South Africa)'),
            Language(name='ar-AE', label='Arabic (Gulf)'),
            Language(name='ar-XA', label='Arabic (Standard)'),
            Language(name='arb', label='Arabic (Standard)'),
            Language(name='eu-ES', label='Basque (Spain)'),
            Language(name='bg-BG', label='Bulgarian (Bulgaria)'),
            Language(name='ca-ES', label='Catalan (Spain)'),
            Language(name='yue-CN', label='Chinese Cantonese'),
            Language(name='yue-HK', label='Chinese Cantonese (Hong Kong)'),
            Language(name='cmn-CN', label='Chinese Mandarin'),
            Language(name='cmn-TW', label='Chinese Mandarin (Taiwan)'),
            Language(name='cs-CZ', label='Czech (Czech Republic)'),
            Language(name='da-DK', label='Danish (Denmark)'),
            Language(name='nl-BE', label='Dutch (Belgium)'),
            Language(name='nl-NL', label='Dutch (Netherlands)'),
            Language(name='en-AU', label='English (Australia)'),
            Language(name='en-IN', label='English (India)'),
            Language(name='en-NZ', label='English (New Zealand)'),
            Language(name='en-ZA', label='English (South African)'),
            Language(name='en-GB', label='English (UK)'),
            Language(name='en-US', label='English (US)'),
            Language(name='en-GB-WLS', label='English (Welsh)'),
            Language(name='fil-PH', label='Filipino (Philippines)'),
            Language(name='fi-FI', label='Finnish (Finland)'),
            Language(name='fr-CA', label='French (Canada)'),
            Language(name='fr-FR', label='French (France)'),
            Language(name='gl-ES', label='Galician (Spain)'),
            Language(name='de-AT', label='German (Austria)'),
            Language(name='de-DE', label='German (Germany)'),
            Language(name='el-GR', label='Greek (Greece)'),
            Language(name='he-IL', label='Hebrew (Israel)'),
            Language(name='hi-IN', label='Hindi (India)'),
            Language(name='hu-HU', label='Hungarian (Hungary)'),
            Language(name='is-IS', label='Icelandic (Iceland)'),
            Language(name='id-ID', label='Indonesian (Indonesia)'),
            Language(name='it-IT', label='Italian (Italy)'),
            Language(name='ja-JP', label='Japanese (Japan)'),
            Language(name='ko-KR', label='Korean (South Korea)'),
            Language(name='lv-LV', label='Latvian (Latvia)'),
            Language(name='lt-LT', label='Lithuanian (Lithuania)'),
            Language(name='ms-MY', label='Malay (Malaysia)'),
            Language(name='ml-IN', label='Malayalam (India)'),
            Language(name='mr-IN', label='Marathi (India)'),
            Language(name='nb-NO', label='Norwegian (Norway)'),
            Language(name='pl-PL', label='Polish (Poland)'),
            Language(name='pt-BR', label='Portuguese (Brazil)'),
            Language(name='pt-PT', label='Portuguese (Portugal)'),
            Language(name='pa-IN', label='Punjabi (India)'),
            Language(name='ro-RO', label='Romanian (Romania)'),
            Language(name='ru-RU', label='Russian (Russia)'),
            Language(name='sr-RS', label='Serbian (Cyrillic)'),
            Language(name='sk-SK', label='Slovak (Slovakia)'),
            Language(name='es-MX', label='Spanish (Mexico)'),
            Language(name='es-ES', label='Spanish (Spain)'),
            Language(name='es-US', label='Spanish (US)'),
            Language(name='sv-SE', label='Swedish (Sweden)'),
            Language(name='ta-IN', label='Tamil (India)'),
            Language(name='te-IN', label='Telugu (India)'),
            Language(name='th-TH', label='Thai (Thailand)'),
            Language(name='tr-TR', label='Turkish (Turkey)'),
            Language(name='uk-UA', label='Ukrainian (Ukraine)'),
            Language(name='vi-VN', label='Vietnamese (Vietnam)'),
            Language(name='cy-GB', label='Welsh'),
        ]

    def _init_voices(self):
        if len(self._voices):
            return

        self._voices = [
            Voice(name='Google.af-ZA-Standard-A', label='Google.af-ZA-Standard-A', language=self.get_language('af-ZA'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Hala-Neural ', label='Polly.Hala-Neural ', language=self.get_language('ar-AE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ar-XA-Standard-A', label='Google.ar-XA-Standard-A', language=self.get_language('ar-XA'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ar-XA-Standard-B', label='Google.ar-XA-Standard-B', language=self.get_language('ar-XA'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ar-XA-Standard-C', label='Google.ar-XA-Standard-C', language=self.get_language('ar-XA'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ar-XA-Standard-D', label='Google.ar-XA-Standard-D', language=self.get_language('ar-XA'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ar-XA-Wavenet-A', label='Google.ar-XA-Wavenet-A', language=self.get_language('ar-XA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ar-XA-Wavenet-B', label='Google.ar-XA-Wavenet-B', language=self.get_language('ar-XA'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ar-XA-Wavenet-C', label='Google.ar-XA-Wavenet-C', language=self.get_language('ar-XA'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ar-XA-Wavenet-D', label='Google.ar-XA-Wavenet-D', language=self.get_language('ar-XA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Zeina', label='Polly.Zeina', language=self.get_language('arb'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Google.bg-BG-Standard-A', label='Google.bg-BG-Standard-A', language=self.get_language('bg-BG'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ca-ES-Standard-A', label='Google.ca-ES-Standard-A', language=self.get_language('ca-ES'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Arlet-Neural', label='Polly.Arlet-Neural', language=self.get_language('ca-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.cmn-CN-Standard-A', label='Google.cmn-CN-Standard-A',
                  language=self.get_language('cmn-CN'), speech_type='Standard', gender='Female'),
            Voice(name='Google.cmn-CN-Standard-B', label='Google.cmn-CN-Standard-B',
                  language=self.get_language('cmn-CN'), speech_type='Standard', gender='Male'),
            Voice(name='Google.cmn-CN-Standard-C', label='Google.cmn-CN-Standard-C',
                  language=self.get_language('cmn-CN'), speech_type='Standard', gender='Male'),
            Voice(name='Google.cmn-CN-Standard-D', label='Google.cmn-CN-Standard-D',
                  language=self.get_language('cmn-CN'), speech_type='Standard', gender='Female'),
            Voice(name='Google.cmn-CN-Wavenet-A', label='Google.cmn-CN-Wavenet-A', language=self.get_language('cmn-CN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.cmn-CN-Wavenet-B', label='Google.cmn-CN-Wavenet-B', language=self.get_language('cmn-CN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.cmn-CN-Wavenet-C', label='Google.cmn-CN-Wavenet-C', language=self.get_language('cmn-CN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.cmn-CN-Wavenet-D', label='Google.cmn-CN-Wavenet-D', language=self.get_language('cmn-CN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Zhiyu', label='Polly.Zhiyu', language=self.get_language('cmn-CN'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Zhiyu-Neural', label='Polly.Zhiyu-Neural', language=self.get_language('cmn-CN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.cmn-TW-Standard-A', label='Google.cmn-TW-Standard-A',
                  language=self.get_language('cmn-TW'), speech_type='Standard', gender='Female'),
            Voice(name='Google.cmn-TW-Standard-B', label='Google.cmn-TW-Standard-B',
                  language=self.get_language('cmn-TW'), speech_type='Standard', gender='Male'),
            Voice(name='Google.cmn-TW-Standard-C', label='Google.cmn-TW-Standard-C',
                  language=self.get_language('cmn-TW'), speech_type='Standard', gender='Male'),
            Voice(name='Google.cmn-TW-Wavenet-A', label='Google.cmn-TW-Wavenet-A', language=self.get_language('cmn-TW'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.cmn-TW-Wavenet-B', label='Google.cmn-TW-Wavenet-B', language=self.get_language('cmn-TW'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.cmn-TW-Wavenet-C', label='Google.cmn-TW-Wavenet-C', language=self.get_language('cmn-TW'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.cs-CZ-Standard-A', label='Google.cs-CZ-Standard-A', language=self.get_language('cs-CZ'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.cs-CZ-Wavenet-A', label='Google.cs-CZ-Wavenet-A', language=self.get_language('cs-CZ'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Gwyneth', label='Polly.Gwyneth', language=self.get_language('cy-GB'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.da-DK-Standard-A', label='Google.da-DK-Standard-A', language=self.get_language('da-DK'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.da-DK-Standard-C', label='Google.da-DK-Standard-C', language=self.get_language('da-DK'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.da-DK-Standard-D', label='Google.da-DK-Standard-D', language=self.get_language('da-DK'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.da-DK-Standard-E', label='Google.da-DK-Standard-E', language=self.get_language('da-DK'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.da-DK-Wavenet-A', label='Google.da-DK-Wavenet-A', language=self.get_language('da-DK'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.da-DK-Wavenet-C', label='Google.da-DK-Wavenet-C', language=self.get_language('da-DK'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.da-DK-Wavenet-D', label='Google.da-DK-Wavenet-D', language=self.get_language('da-DK'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.da-DK-Wavenet-E', label='Google.da-DK-Wavenet-E', language=self.get_language('da-DK'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Mads', label='Polly.Mads', language=self.get_language('da-DK'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Naja', label='Polly.Naja', language=self.get_language('da-DK'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Hannah-Neural', label='Polly.Hannah-Neural', language=self.get_language('de-AT'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.de-DE-Neural2-B', label='Google.de-DE-Neural2-B', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.de-DE-Neural2-C', label='Google.de-DE-Neural2-C', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.de-DE-Neural2-D', label='Google.de-DE-Neural2-D', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.de-DE-Neural2-F', label='Google.de-DE-Neural2-F', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.de-DE-Standard-A', label='Google.de-DE-Standard-A', language=self.get_language('de-DE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.de-DE-Standard-B', label='Google.de-DE-Standard-B', language=self.get_language('de-DE'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.de-DE-Standard-C', label='Google.de-DE-Standard-C', language=self.get_language('de-DE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.de-DE-Standard-D', label='Google.de-DE-Standard-D', language=self.get_language('de-DE'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.de-DE-Standard-E', label='Google.de-DE-Standard-E', language=self.get_language('de-DE'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.de-DE-Standard-F', label='Google.de-DE-Standard-F', language=self.get_language('de-DE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.de-DE-Wavenet-A', label='Google.de-DE-Wavenet-A', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.de-DE-Wavenet-B', label='Google.de-DE-Wavenet-B', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.de-DE-Wavenet-C', label='Google.de-DE-Wavenet-C', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.de-DE-Wavenet-D', label='Google.de-DE-Wavenet-D', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.de-DE-Wavenet-E', label='Google.de-DE-Wavenet-E', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.de-DE-Wavenet-F', label='Google.de-DE-Wavenet-F', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Man', label='Man', language=self.get_language('de-DE'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Daniel-Neural', label='Polly.Daniel-Neural', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Hans', label='Polly.Hans', language=self.get_language('de-DE'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Marlene', label='Polly.Marlene', language=self.get_language('de-DE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Vicki', label='Polly.Vicki', language=self.get_language('de-DE'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Vicki-Neural', label='Polly.Vicki-Neural', language=self.get_language('de-DE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Woman', label='Woman', language=self.get_language('de-DE'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Google.el-GR-Standard-A', label='Google.el-GR-Standard-A', language=self.get_language('el-GR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.el-GR-Wavenet-A', label='Google.el-GR-Wavenet-A', language=self.get_language('el-GR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-AU-Neural2-A', label='Google.en-AU-Neural2-A', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-AU-Neural2-B', label='Google.en-AU-Neural2-B', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-AU-Neural2-C', label='Google.en-AU-Neural2-C', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-AU-Neural2-D', label='Google.en-AU-Neural2-D', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-AU-Standard-A', label='Google.en-AU-Standard-A', language=self.get_language('en-AU'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-AU-Standard-B', label='Google.en-AU-Standard-B', language=self.get_language('en-AU'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-AU-Standard-C', label='Google.en-AU-Standard-C', language=self.get_language('en-AU'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-AU-Standard-D', label='Google.en-AU-Standard-D', language=self.get_language('en-AU'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-AU-Wavenet-A', label='Google.en-AU-Wavenet-A', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-AU-Wavenet-B', label='Google.en-AU-Wavenet-B', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-AU-Wavenet-C', label='Google.en-AU-Wavenet-C', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-AU-Wavenet-D', label='Google.en-AU-Wavenet-D', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Nicole', label='Polly.Nicole', language=self.get_language('en-AU'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Olivia-Neural', label='Polly.Olivia-Neural', language=self.get_language('en-AU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Russell', label='Polly.Russell', language=self.get_language('en-AU'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-GB-Neural2-A', label='Google.en-GB-Neural2-A', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-GB-Neural2-B', label='Google.en-GB-Neural2-B', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-GB-Neural2-C', label='Google.en-GB-Neural2-C', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-GB-Neural2-D', label='Google.en-GB-Neural2-D', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-GB-Neural2-F', label='Google.en-GB-Neural2-F', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-GB-Standard-A', label='Google.en-GB-Standard-A', language=self.get_language('en-GB'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-GB-Standard-B', label='Google.en-GB-Standard-B', language=self.get_language('en-GB'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-GB-Standard-C', label='Google.en-GB-Standard-C', language=self.get_language('en-GB'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-GB-Standard-D', label='Google.en-GB-Standard-D', language=self.get_language('en-GB'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-GB-Standard-F', label='Google.en-GB-Standard-F', language=self.get_language('en-GB'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-GB-Wavenet-A', label='Google.en-GB-Wavenet-A', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-GB-Wavenet-B', label='Google.en-GB-Wavenet-B', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-GB-Wavenet-C', label='Google.en-GB-Wavenet-C', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-GB-Wavenet-D', label='Google.en-GB-Wavenet-D', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-GB-Wavenet-F', label='Google.en-GB-Wavenet-F', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Man', label='Man', language=self.get_language('en-GB'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Amy', label='Polly.Amy', language=self.get_language('en-GB'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Amy-Neural', label='Polly.Amy-Neural', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Arthur-Neural', label='Polly.Arthur-Neural', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Brian', label='Polly.Brian', language=self.get_language('en-GB'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Brian-Neural', label='Polly.Brian-Neural', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Emma', label='Polly.Emma', language=self.get_language('en-GB'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Emma-Neural', label='Polly.Emma-Neural', language=self.get_language('en-GB'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Woman', label='Woman', language=self.get_language('en-GB'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Polly.Geraint', label='Polly.Geraint', language=self.get_language('en-GB-WLS'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-IN-Standard-A', label='Google.en-IN-Standard-A', language=self.get_language('en-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-IN-Standard-B', label='Google.en-IN-Standard-B', language=self.get_language('en-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-IN-Standard-C', label='Google.en-IN-Standard-C', language=self.get_language('en-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-IN-Standard-D', label='Google.en-IN-Standard-D', language=self.get_language('en-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-IN-Wavenet-A', label='Google.en-IN-Wavenet-A', language=self.get_language('en-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-IN-Wavenet-B', label='Google.en-IN-Wavenet-B', language=self.get_language('en-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-IN-Wavenet-C', label='Google.en-IN-Wavenet-C', language=self.get_language('en-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-IN-Wavenet-D', label='Google.en-IN-Wavenet-D', language=self.get_language('en-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Aditi ', label='Polly.Aditi ', language=self.get_language('en-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Kajal-Neural ', label='Polly.Kajal-Neural ', language=self.get_language('en-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Raveena', label='Polly.Raveena', language=self.get_language('en-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Aria-Neural', label='Polly.Aria-Neural', language=self.get_language('en-NZ'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Neural2-A', label='Google.en-US-Neural2-A', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Neural2-C', label='Google.en-US-Neural2-C', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Neural2-D', label='Google.en-US-Neural2-D', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Neural2-E', label='Google.en-US-Neural2-E', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Neural2-F', label='Google.en-US-Neural2-F', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Neural2-G', label='Google.en-US-Neural2-G', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Neural2-H', label='Google.en-US-Neural2-H', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Neural2-I', label='Google.en-US-Neural2-I', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Neural2-J', label='Google.en-US-Neural2-J', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Standard-A', label='Google.en-US-Standard-A', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-US-Standard-B', label='Google.en-US-Standard-B', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-US-Standard-C', label='Google.en-US-Standard-C', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-US-Standard-D', label='Google.en-US-Standard-D', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-US-Standard-E', label='Google.en-US-Standard-E', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-US-Standard-F', label='Google.en-US-Standard-F', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-US-Standard-G', label='Google.en-US-Standard-G', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-US-Standard-H', label='Google.en-US-Standard-H', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.en-US-Standard-I', label='Google.en-US-Standard-I', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-US-Standard-J', label='Google.en-US-Standard-J', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.en-US-Wavenet-A', label='Google.en-US-Wavenet-A', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Wavenet-B', label='Google.en-US-Wavenet-B', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Wavenet-C', label='Google.en-US-Wavenet-C', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Wavenet-D', label='Google.en-US-Wavenet-D', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Wavenet-E', label='Google.en-US-Wavenet-E', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Wavenet-F', label='Google.en-US-Wavenet-F', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Wavenet-G', label='Google.en-US-Wavenet-G', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Wavenet-H', label='Google.en-US-Wavenet-H', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.en-US-Wavenet-I', label='Google.en-US-Wavenet-I', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.en-US-Wavenet-J', label='Google.en-US-Wavenet-J', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Man', label='Man', language=self.get_language('en-US'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Ivy', label='Polly.Ivy', language=self.get_language('en-US'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Ivy-Neural', label='Polly.Ivy-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Joanna', label='Polly.Joanna', language=self.get_language('en-US'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Joanna-Neural', label='Polly.Joanna-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Joey', label='Polly.Joey', language=self.get_language('en-US'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Joey-Neural', label='Polly.Joey-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Justin', label='Polly.Justin', language=self.get_language('en-US'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Justin-Neural', label='Polly.Justin-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Kendra', label='Polly.Kendra', language=self.get_language('en-US'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Kendra-Neural', label='Polly.Kendra-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Kevin-Neural', label='Polly.Kevin-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male (child)'),
            Voice(name='Polly.Kimberly', label='Polly.Kimberly', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Kimberly-Neural', label='Polly.Kimberly-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Matthew', label='Polly.Matthew', language=self.get_language('en-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Polly.Matthew-Neural', label='Polly.Matthew-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Ruth-Neural', label='Polly.Ruth-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Salli', label='Polly.Salli', language=self.get_language('en-US'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Salli-Neural', label='Polly.Salli-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Stephen-Neural', label='Polly.Stephen-Neural', language=self.get_language('en-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Woman', label='Woman', language=self.get_language('en-US'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Polly.Ayanda-Neural', label='Polly.Ayanda-Neural', language=self.get_language('en-ZA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-ES-Neural2-A', label='Google.es-ES-Neural2-A', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-ES-Neural2-B', label='Google.es-ES-Neural2-B', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.es-ES-Neural2-C', label='Google.es-ES-Neural2-C', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-ES-Neural2-D', label='Google.es-ES-Neural2-D', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-ES-Neural2-E', label='Google.es-ES-Neural2-E', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-ES-Neural2-F', label='Google.es-ES-Neural2-F', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.es-ES-Standard-B', label='Google.es-ES-Standard-B', language=self.get_language('es-ES'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.es-ES-Standard-C', label='Google.es-ES-Standard-C', language=self.get_language('es-ES'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.es-ES-Standard-D', label='Google.es-ES-Standard-D', language=self.get_language('es-ES'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.es-ES-Wavenet-B', label='Google.es-ES-Wavenet-B', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.es-ES-Wavenet-C', label='Google.es-ES-Wavenet-C', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-ES-Wavenet-D', label='Google.es-ES-Wavenet-D', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Man', label='Man', language=self.get_language('es-ES'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Conchita', label='Polly.Conchita', language=self.get_language('es-ES'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Enrique', label='Polly.Enrique', language=self.get_language('es-ES'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Polly.Lucia', label='Polly.Lucia', language=self.get_language('es-ES'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Lucia-Neural', label='Polly.Lucia-Neural', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Sergio-Neural', label='Polly.Sergio-Neural', language=self.get_language('es-ES'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Woman', label='Woman', language=self.get_language('es-ES'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Man', label='Man', language=self.get_language('es-MX'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Andres-Neural', label='Polly.Andres-Neural', language=self.get_language('es-MX'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Mia', label='Polly.Mia', language=self.get_language('es-MX'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Mia-Neural', label='Polly.Mia-Neural', language=self.get_language('es-MX'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Woman', label='Woman', language=self.get_language('es-MX'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Google.es-US-Neural2-A', label='Google.es-US-Neural2-A', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-US-Neural2-B', label='Google.es-US-Neural2-B', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.es-US-Neural2-C', label='Google.es-US-Neural2-C', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.es-US-Standard-A', label='Google.es-US-Standard-A', language=self.get_language('es-US'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.es-US-Standard-B', label='Google.es-US-Standard-B', language=self.get_language('es-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.es-US-Standard-C', label='Google.es-US-Standard-C', language=self.get_language('es-US'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.es-US-Wavenet-A', label='Google.es-US-Wavenet-A', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.es-US-Wavenet-B', label='Google.es-US-Wavenet-B', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.es-US-Wavenet-C', label='Google.es-US-Wavenet-C', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Man', label='Man', language=self.get_language('es-US'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Lupe', label='Polly.Lupe', language=self.get_language('es-US'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Lupe-Neural', label='Polly.Lupe-Neural', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Miguel', label='Polly.Miguel', language=self.get_language('es-US'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Pedro-Neural', label='Polly.Pedro-Neural', language=self.get_language('es-US'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Penélope/Polly.Penelope', label='Polly.Penélope/Polly.Penelope',
                  language=self.get_language('es-US'), speech_type='Standard', gender='Female'),
            Voice(name='Woman', label='Woman', language=self.get_language('es-US'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Google.eu-ES-Standard-A', label='Google.eu-ES-Standard-A', language=self.get_language('eu-ES'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.fi-FI-Standard-A', label='Google.fi-FI-Standard-A', language=self.get_language('fi-FI'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.fi-FI-Wavenet-A', label='Google.fi-FI-Wavenet-A', language=self.get_language('fi-FI'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Suvi-Neural', label='Polly.Suvi-Neural', language=self.get_language('fi-FI'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fil-PH-Standard-A', label='Google.fil-PH-Standard-A',
                  language=self.get_language('fil-PH'), speech_type='Standard', gender='Female'),
            Voice(name='Google.fil-PH-Standard-B', label='Google.fil-PH-Standard-B',
                  language=self.get_language('fil-PH'), speech_type='Standard', gender='Female'),
            Voice(name='Google.fil-PH-Standard-C', label='Google.fil-PH-Standard-C',
                  language=self.get_language('fil-PH'), speech_type='Standard', gender='Male'),
            Voice(name='Google.fil-PH-Standard-D', label='Google.fil-PH-Standard-D',
                  language=self.get_language('fil-PH'), speech_type='Standard', gender='Male'),
            Voice(name='Google.fil-PH-Wavenet-A', label='Google.fil-PH-Wavenet-A', language=self.get_language('fil-PH'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fil-PH-Wavenet-B', label='Google.fil-PH-Wavenet-B', language=self.get_language('fil-PH'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fil-PH-Wavenet-C', label='Google.fil-PH-Wavenet-C', language=self.get_language('fil-PH'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fil-PH-Wavenet-D', label='Google.fil-PH-Wavenet-D', language=self.get_language('fil-PH'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-CA-Neural2-A', label='Google.fr-CA-Neural2-A', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-CA-Neural2-B', label='Google.fr-CA-Neural2-B', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-CA-Neural2-C', label='Google.fr-CA-Neural2-C', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-CA-Neural2-D', label='Google.fr-CA-Neural2-D', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-CA-Standard-A', label='Google.fr-CA-Standard-A', language=self.get_language('fr-CA'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.fr-CA-Standard-B', label='Google.fr-CA-Standard-B', language=self.get_language('fr-CA'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.fr-CA-Standard-C', label='Google.fr-CA-Standard-C', language=self.get_language('fr-CA'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.fr-CA-Standard-D', label='Google.fr-CA-Standard-D', language=self.get_language('fr-CA'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.fr-CA-Wavenet-A', label='Google.fr-CA-Wavenet-A', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-CA-Wavenet-B', label='Google.fr-CA-Wavenet-B', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-CA-Wavenet-C', label='Google.fr-CA-Wavenet-C', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-CA-Wavenet-D', label='Google.fr-CA-Wavenet-D', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Chantal', label='Polly.Chantal', language=self.get_language('fr-CA'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Gabrielle-Neural', label='Polly.Gabrielle-Neural', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Liam-Neural', label='Polly.Liam-Neural', language=self.get_language('fr-CA'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-FR-Neural2-A', label='Google.fr-FR-Neural2-A', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-FR-Neural2-B', label='Google.fr-FR-Neural2-B', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-FR-Neural2-C', label='Google.fr-FR-Neural2-C', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-FR-Neural2-D', label='Google.fr-FR-Neural2-D', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-FR-Neural2-E', label='Google.fr-FR-Neural2-E', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-FR-Standard-A', label='Google.fr-FR-Standard-A', language=self.get_language('fr-FR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.fr-FR-Standard-B', label='Google.fr-FR-Standard-B', language=self.get_language('fr-FR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.fr-FR-Standard-C', label='Google.fr-FR-Standard-C', language=self.get_language('fr-FR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.fr-FR-Standard-D', label='Google.fr-FR-Standard-D', language=self.get_language('fr-FR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.fr-FR-Standard-E', label='Google.fr-FR-Standard-E', language=self.get_language('fr-FR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.fr-FR-Wavenet-A', label='Google.fr-FR-Wavenet-A', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-FR-Wavenet-B', label='Google.fr-FR-Wavenet-B', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-FR-Wavenet-C', label='Google.fr-FR-Wavenet-C', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.fr-FR-Wavenet-D', label='Google.fr-FR-Wavenet-D', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.fr-FR-Wavenet-E', label='Google.fr-FR-Wavenet-E', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Man', label='Man', language=self.get_language('fr-FR'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Céline/Polly.Celine', label='Polly.Céline/Polly.Celine',
                  language=self.get_language('fr-FR'), speech_type='Standard', gender='Female'),
            Voice(name='Polly.Lea-Neural', label='Polly.Lea-Neural', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Léa/Polly.Lea', label='Polly.Léa/Polly.Lea', language=self.get_language('fr-FR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Mathieu', label='Polly.Mathieu', language=self.get_language('fr-FR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Polly.Remi-Neural', label='Polly.Remi-Neural', language=self.get_language('fr-FR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Woman', label='Woman', language=self.get_language('fr-FR'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Google.gl-ES-Standard-A', label='Google.gl-ES-Standard-A', language=self.get_language('gl-ES'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.he-IL-Standard-A', label='Google.he-IL-Standard-A', language=self.get_language('he-IL'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.he-IL-Standard-B', label='Google.he-IL-Standard-B', language=self.get_language('he-IL'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.he-IL-Standard-C', label='Google.he-IL-Standard-C', language=self.get_language('he-IL'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.he-IL-Standard-D', label='Google.he-IL-Standard-D', language=self.get_language('he-IL'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.he-IL-Wavenet-A', label='Google.he-IL-Wavenet-A', language=self.get_language('he-IL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.he-IL-Wavenet-B', label='Google.he-IL-Wavenet-B', language=self.get_language('he-IL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.he-IL-Wavenet-C', label='Google.he-IL-Wavenet-C', language=self.get_language('he-IL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.he-IL-Wavenet-D', label='Google.he-IL-Wavenet-D', language=self.get_language('he-IL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.hi-IN-Neural2-A', label='Google.hi-IN-Neural2-A', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.hi-IN-Neural2-B', label='Google.hi-IN-Neural2-B', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.hi-IN-Neural2-C', label='Google.hi-IN-Neural2-C', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.hi-IN-Neural2-D', label='Google.hi-IN-Neural2-D', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.hi-IN-Standard-A', label='Google.hi-IN-Standard-A', language=self.get_language('hi-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.hi-IN-Standard-B', label='Google.hi-IN-Standard-B', language=self.get_language('hi-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.hi-IN-Standard-C', label='Google.hi-IN-Standard-C', language=self.get_language('hi-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.hi-IN-Standard-D', label='Google.hi-IN-Standard-D', language=self.get_language('hi-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.hi-IN-Wavenet-A', label='Google.hi-IN-Wavenet-A', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.hi-IN-Wavenet-B', label='Google.hi-IN-Wavenet-B', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.hi-IN-Wavenet-C', label='Google.hi-IN-Wavenet-C', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.hi-IN-Wavenet-D', label='Google.hi-IN-Wavenet-D', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Aditi ', label='Polly.Aditi ', language=self.get_language('hi-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Kajal-Neural ', label='Polly.Kajal-Neural ', language=self.get_language('hi-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.hu-HU-Standard-A', label='Google.hu-HU-Standard-A', language=self.get_language('hu-HU'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.hu-HU-Wavenet-A', label='Google.hu-HU-Wavenet-A', language=self.get_language('hu-HU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.id-ID-Standard-A', label='Google.id-ID-Standard-A', language=self.get_language('id-ID'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.id-ID-Standard-B', label='Google.id-ID-Standard-B', language=self.get_language('id-ID'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.id-ID-Standard-C', label='Google.id-ID-Standard-C', language=self.get_language('id-ID'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.id-ID-Standard-D', label='Google.id-ID-Standard-D', language=self.get_language('id-ID'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.id-ID-Wavenet-A', label='Google.id-ID-Wavenet-A', language=self.get_language('id-ID'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.id-ID-Wavenet-B', label='Google.id-ID-Wavenet-B', language=self.get_language('id-ID'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.id-ID-Wavenet-C', label='Google.id-ID-Wavenet-C', language=self.get_language('id-ID'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.id-ID-Wavenet-D', label='Google.id-ID-Wavenet-D', language=self.get_language('id-ID'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.is-IS-Standard-A', label='Google.is-IS-Standard-A', language=self.get_language('is-IS'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Dóra/Polly.Dora', label='Polly.Dóra/Polly.Dora', language=self.get_language('is-IS'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Karl', label='Polly.Karl', language=self.get_language('is-IS'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Google.it-IT-Neural2-A', label='Google.it-IT-Neural2-A', language=self.get_language('it-IT'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.it-IT-Neural2-C', label='Google.it-IT-Neural2-C', language=self.get_language('it-IT'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.it-IT-Standard-B', label='Google.it-IT-Standard-B', language=self.get_language('it-IT'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.it-IT-Standard-C', label='Google.it-IT-Standard-C', language=self.get_language('it-IT'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.it-IT-Standard-D', label='Google.it-IT-Standard-D', language=self.get_language('it-IT'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.it-IT-Wavenet-B', label='Google.it-IT-Wavenet-B', language=self.get_language('it-IT'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.it-IT-Wavenet-C', label='Google.it-IT-Wavenet-C', language=self.get_language('it-IT'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.it-IT-Wavenet-D', label='Google.it-IT-Wavenet-D', language=self.get_language('it-IT'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Man', label='Man', language=self.get_language('it-IT'), speech_type='Basic', gender='Male'),
            Voice(name='Polly.Adriano-Neural', label='Polly.Adriano-Neural', language=self.get_language('it-IT'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Bianca', label='Polly.Bianca', language=self.get_language('it-IT'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Bianca-Neural', label='Polly.Bianca-Neural', language=self.get_language('it-IT'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Carla', label='Polly.Carla', language=self.get_language('it-IT'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Giorgio', label='Polly.Giorgio', language=self.get_language('it-IT'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Woman', label='Woman', language=self.get_language('it-IT'), speech_type='Basic',
                  gender='Female'),
            Voice(name='Google.ja-JP-Standard-B', label='Google.ja-JP-Standard-B', language=self.get_language('ja-JP'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ja-JP-Standard-C', label='Google.ja-JP-Standard-C', language=self.get_language('ja-JP'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ja-JP-Standard-D', label='Google.ja-JP-Standard-D', language=self.get_language('ja-JP'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ja-JP-Wavenet-B', label='Google.ja-JP-Wavenet-B', language=self.get_language('ja-JP'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ja-JP-Wavenet-C', label='Google.ja-JP-Wavenet-C', language=self.get_language('ja-JP'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ja-JP-Wavenet-D', label='Google.ja-JP-Wavenet-D', language=self.get_language('ja-JP'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Kazuha-Neural', label='Polly.Kazuha-Neural', language=self.get_language('ja-JP'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Mizuki', label='Polly.Mizuki', language=self.get_language('ja-JP'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Takumi', label='Polly.Takumi', language=self.get_language('ja-JP'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Takumi-Neural', label='Polly.Takumi-Neural', language=self.get_language('ja-JP'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Tomoko-Neural', label='Polly.Tomoko-Neural', language=self.get_language('ja-JP'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ko-KR-Neural2-A', label='Google.ko-KR-Neural2-A', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ko-KR-Neural2-B', label='Google.ko-KR-Neural2-B', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ko-KR-Neural2-C', label='Google.ko-KR-Neural2-C', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ko-KR-Standard-A', label='Google.ko-KR-Standard-A', language=self.get_language('ko-KR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ko-KR-Standard-B', label='Google.ko-KR-Standard-B', language=self.get_language('ko-KR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ko-KR-Standard-C', label='Google.ko-KR-Standard-C', language=self.get_language('ko-KR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ko-KR-Standard-D', label='Google.ko-KR-Standard-D', language=self.get_language('ko-KR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ko-KR-Wavenet-A', label='Google.ko-KR-Wavenet-A', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ko-KR-Wavenet-B', label='Google.ko-KR-Wavenet-B', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ko-KR-Wavenet-C', label='Google.ko-KR-Wavenet-C', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ko-KR-Wavenet-D', label='Google.ko-KR-Wavenet-D', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Seoyeon', label='Polly.Seoyeon', language=self.get_language('ko-KR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Polly.Seoyeon-Neural', label='Polly.Seoyeon-Neural', language=self.get_language('ko-KR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.lt-LT-Standard-A', label='Google.lt-LT-Standard-A', language=self.get_language('lt-LT'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.lv-LV-Standard-A', label='Google.lv-LV-Standard-A', language=self.get_language('lv-LV'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ml-IN-Wavenet-C', label='Google.ml-IN-Wavenet-C', language=self.get_language('ml-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ml-IN-Wavenet-D', label='Google.ml-IN-Wavenet-D', language=self.get_language('ml-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.mr-IN-Standard-A', label='Google.mr-IN-Standard-A', language=self.get_language('mr-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.mr-IN-Standard-B', label='Google.mr-IN-Standard-B', language=self.get_language('mr-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.mr-IN-Standard-C', label='Google.mr-IN-Standard-C', language=self.get_language('mr-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.mr-IN-Wavenet-A', label='Google.mr-IN-Wavenet-A', language=self.get_language('mr-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.mr-IN-Wavenet-B', label='Google.mr-IN-Wavenet-B', language=self.get_language('mr-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.mr-IN-Wavenet-C', label='Google.mr-IN-Wavenet-C', language=self.get_language('mr-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ms-MY-Standard-A', label='Google.ms-MY-Standard-A', language=self.get_language('ms-MY'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ms-MY-Standard-B', label='Google.ms-MY-Standard-B', language=self.get_language('ms-MY'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ms-MY-Standard-C', label='Google.ms-MY-Standard-C', language=self.get_language('ms-MY'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ms-MY-Standard-D', label='Google.ms-MY-Standard-D', language=self.get_language('ms-MY'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ms-MY-Wavenet-A', label='Google.ms-MY-Wavenet-A', language=self.get_language('ms-MY'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ms-MY-Wavenet-B', label='Google.ms-MY-Wavenet-B', language=self.get_language('ms-MY'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ms-MY-Wavenet-C', label='Google.ms-MY-Wavenet-C', language=self.get_language('ms-MY'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ms-MY-Wavenet-D', label='Google.ms-MY-Wavenet-D', language=self.get_language('ms-MY'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.nb-NO-Standard-A', label='Google.nb-NO-Standard-A', language=self.get_language('nb-NO'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.nb-NO-Standard-B', label='Google.nb-NO-Standard-B', language=self.get_language('nb-NO'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.nb-NO-Standard-C', label='Google.nb-NO-Standard-C', language=self.get_language('nb-NO'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.nb-NO-Standard-D', label='Google.nb-NO-Standard-D', language=self.get_language('nb-NO'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.nb-NO-Standard-E', label='Google.nb-NO-Standard-E', language=self.get_language('nb-NO'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.nb-NO-Wavenet-A', label='Google.nb-NO-Wavenet-A', language=self.get_language('nb-NO'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.nb-NO-Wavenet-B', label='Google.nb-NO-Wavenet-B', language=self.get_language('nb-NO'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.nb-NO-Wavenet-C', label='Google.nb-NO-Wavenet-C', language=self.get_language('nb-NO'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.nb-NO-Wavenet-D', label='Google.nb-NO-Wavenet-D', language=self.get_language('nb-NO'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.nb-NO-Wavenet-E', label='Google.nb-NO-Wavenet-E', language=self.get_language('nb-NO'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Ida-Neural', label='Polly.Ida-Neural', language=self.get_language('nb-NO'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Liv', label='Polly.Liv', language=self.get_language('nb-NO'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Google.nl-BE-Standard-A', label='Google.nl-BE-Standard-A', language=self.get_language('nl-BE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.nl-BE-Standard-B', label='Google.nl-BE-Standard-B', language=self.get_language('nl-BE'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.nl-BE-Wavenet-A', label='Google.nl-BE-Wavenet-A', language=self.get_language('nl-BE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.nl-BE-Wavenet-B', label='Google.nl-BE-Wavenet-B', language=self.get_language('nl-BE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.nl-NL-Standard-A', label='Google.nl-NL-Standard-A', language=self.get_language('nl-NL'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.nl-NL-Standard-B', label='Google.nl-NL-Standard-B', language=self.get_language('nl-NL'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.nl-NL-Standard-C', label='Google.nl-NL-Standard-C', language=self.get_language('nl-NL'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.nl-NL-Standard-D', label='Google.nl-NL-Standard-D', language=self.get_language('nl-NL'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.nl-NL-Standard-E', label='Google.nl-NL-Standard-E', language=self.get_language('nl-NL'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.nl-NL-Wavenet-A', label='Google.nl-NL-Wavenet-A', language=self.get_language('nl-NL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.nl-NL-Wavenet-B', label='Google.nl-NL-Wavenet-B', language=self.get_language('nl-NL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.nl-NL-Wavenet-C', label='Google.nl-NL-Wavenet-C', language=self.get_language('nl-NL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.nl-NL-Wavenet-D', label='Google.nl-NL-Wavenet-D', language=self.get_language('nl-NL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.nl-NL-Wavenet-E', label='Google.nl-NL-Wavenet-E', language=self.get_language('nl-NL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Laura-Neural', label='Polly.Laura-Neural', language=self.get_language('nl-NL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Lotte', label='Polly.Lotte', language=self.get_language('nl-NL'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Ruben', label='Polly.Ruben', language=self.get_language('nl-NL'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Google.pa-IN-Standard-A', label='Google.pa-IN-Standard-A', language=self.get_language('pa-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.pa-IN-Standard-B', label='Google.pa-IN-Standard-B', language=self.get_language('pa-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.pa-IN-Standard-C', label='Google.pa-IN-Standard-C', language=self.get_language('pa-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.pa-IN-Standard-D', label='Google.pa-IN-Standard-D', language=self.get_language('pa-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.pa-IN-Wavenet-A', label='Google.pa-IN-Wavenet-A', language=self.get_language('pa-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pa-IN-Wavenet-B', label='Google.pa-IN-Wavenet-B', language=self.get_language('pa-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pa-IN-Wavenet-C', label='Google.pa-IN-Wavenet-C', language=self.get_language('pa-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pa-IN-Wavenet-D', label='Google.pa-IN-Wavenet-D', language=self.get_language('pa-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pl-PL-Standard-A', label='Google.pl-PL-Standard-A', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pl-PL-Standard-B', label='Google.pl-PL-Standard-B', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pl-PL-Standard-C', label='Google.pl-PL-Standard-C', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pl-PL-Standard-D', label='Google.pl-PL-Standard-D', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pl-PL-Standard-E', label='Google.pl-PL-Standard-E', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pl-PL-Wavenet-A', label='Google.pl-PL-Wavenet-A', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pl-PL-Wavenet-B', label='Google.pl-PL-Wavenet-B', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pl-PL-Wavenet-C', label='Google.pl-PL-Wavenet-C', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pl-PL-Wavenet-D', label='Google.pl-PL-Wavenet-D', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pl-PL-Wavenet-E', label='Google.pl-PL-Wavenet-E', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Ewa', label='Polly.Ewa', language=self.get_language('pl-PL'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Jacek', label='Polly.Jacek', language=self.get_language('pl-PL'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Jan', label='Polly.Jan', language=self.get_language('pl-PL'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Maja', label='Polly.Maja', language=self.get_language('pl-PL'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Ola-Neural', label='Polly.Ola-Neural', language=self.get_language('pl-PL'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pt-BR-Neural2-A', label='Google.pt-BR-Neural2-A', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pt-BR-Neural2-B', label='Google.pt-BR-Neural2-B', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pt-BR-Neural2-C', label='Google.pt-BR-Neural2-C', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pt-BR-Standard-B', label='Google.pt-BR-Standard-B', language=self.get_language('pt-BR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.pt-BR-Standard-C', label='Google.pt-BR-Standard-C', language=self.get_language('pt-BR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.pt-BR-Wavenet-B', label='Google.pt-BR-Wavenet-B', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pt-BR-Wavenet-C', label='Google.pt-BR-Wavenet-C', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Camila', label='Polly.Camila', language=self.get_language('pt-BR'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Camila-Neural', label='Polly.Camila-Neural', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Ricardo', label='Polly.Ricardo', language=self.get_language('pt-BR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Polly.Thiago-Neural', label='Polly.Thiago-Neural', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Vitoria-Neural', label='Polly.Vitoria-Neural', language=self.get_language('pt-BR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Vitória/Polly.Vitoria', label='Polly.Vitória/Polly.Vitoria',
                  language=self.get_language('pt-BR'), speech_type='Standard', gender='Female'),
            Voice(name='Google.pt-PT-Standard-A', label='Google.pt-PT-Standard-A', language=self.get_language('pt-PT'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.pt-PT-Standard-B', label='Google.pt-PT-Standard-B', language=self.get_language('pt-PT'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.pt-PT-Standard-C', label='Google.pt-PT-Standard-C', language=self.get_language('pt-PT'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.pt-PT-Standard-D', label='Google.pt-PT-Standard-D', language=self.get_language('pt-PT'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.pt-PT-Wavenet-A', label='Google.pt-PT-Wavenet-A', language=self.get_language('pt-PT'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.pt-PT-Wavenet-B', label='Google.pt-PT-Wavenet-B', language=self.get_language('pt-PT'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pt-PT-Wavenet-C', label='Google.pt-PT-Wavenet-C', language=self.get_language('pt-PT'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.pt-PT-Wavenet-D', label='Google.pt-PT-Wavenet-D', language=self.get_language('pt-PT'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Cristiano', label='Polly.Cristiano', language=self.get_language('pt-PT'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Polly.Ines-Neural', label='Polly.Ines-Neural', language=self.get_language('pt-PT'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Inês/Polly.Ines', label='Polly.Inês/Polly.Ines', language=self.get_language('pt-PT'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ro-RO-Standard-A', label='Google.ro-RO-Standard-A', language=self.get_language('ro-RO'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ro-RO-Wavenet-A', label='Google.ro-RO-Wavenet-A', language=self.get_language('ro-RO'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Carmen', label='Polly.Carmen', language=self.get_language('ro-RO'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Google.ru-RU-Standard-A', label='Google.ru-RU-Standard-A', language=self.get_language('ru-RU'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ru-RU-Standard-B', label='Google.ru-RU-Standard-B', language=self.get_language('ru-RU'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ru-RU-Standard-C', label='Google.ru-RU-Standard-C', language=self.get_language('ru-RU'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ru-RU-Standard-D', label='Google.ru-RU-Standard-D', language=self.get_language('ru-RU'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ru-RU-Standard-E', label='Google.ru-RU-Standard-E', language=self.get_language('ru-RU'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ru-RU-Wavenet-A', label='Google.ru-RU-Wavenet-A', language=self.get_language('ru-RU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ru-RU-Wavenet-B', label='Google.ru-RU-Wavenet-B', language=self.get_language('ru-RU'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ru-RU-Wavenet-C', label='Google.ru-RU-Wavenet-C', language=self.get_language('ru-RU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ru-RU-Wavenet-D', label='Google.ru-RU-Wavenet-D', language=self.get_language('ru-RU'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.ru-RU-Wavenet-E', label='Google.ru-RU-Wavenet-E', language=self.get_language('ru-RU'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Polly.Maxim', label='Polly.Maxim', language=self.get_language('ru-RU'), speech_type='Standard',
                  gender='Male'),
            Voice(name='Polly.Tatyana', label='Polly.Tatyana', language=self.get_language('ru-RU'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.sk-SK-Standard-A', label='Google.sk-SK-Standard-A', language=self.get_language('sk-SK'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.sk-SK-Wavenet-A', label='Google.sk-SK-Wavenet-A', language=self.get_language('sk-SK'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.sr-RS-Standard-A', label='Google.sr-RS-Standard-A', language=self.get_language('sr-RS'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.sv-SE-Standard-A', label='Google.sv-SE-Standard-A', language=self.get_language('sv-SE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.sv-SE-Standard-B', label='Google.sv-SE-Standard-B', language=self.get_language('sv-SE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.sv-SE-Standard-C', label='Google.sv-SE-Standard-C', language=self.get_language('sv-SE'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.sv-SE-Standard-D', label='Google.sv-SE-Standard-D', language=self.get_language('sv-SE'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.sv-SE-Standard-E', label='Google.sv-SE-Standard-E', language=self.get_language('sv-SE'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.sv-SE-Wavenet-A', label='Google.sv-SE-Wavenet-A', language=self.get_language('sv-SE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.sv-SE-Wavenet-B', label='Google.sv-SE-Wavenet-B', language=self.get_language('sv-SE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.sv-SE-Wavenet-C', label='Google.sv-SE-Wavenet-C', language=self.get_language('sv-SE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.sv-SE-Wavenet-D', label='Google.sv-SE-Wavenet-D', language=self.get_language('sv-SE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.sv-SE-Wavenet-E', label='Google.sv-SE-Wavenet-E', language=self.get_language('sv-SE'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Astrid', label='Polly.Astrid', language=self.get_language('sv-SE'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Polly.Elin-Neural', label='Polly.Elin-Neural', language=self.get_language('sv-SE'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ta-IN-Standard-C', label='Google.ta-IN-Standard-C', language=self.get_language('ta-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.ta-IN-Standard-D', label='Google.ta-IN-Standard-D', language=self.get_language('ta-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.ta-IN-Wavenet-C', label='Google.ta-IN-Wavenet-C', language=self.get_language('ta-IN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.ta-IN-Wavenet-D', label='Google.ta-IN-Wavenet-D', language=self.get_language('ta-IN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.te-IN-Standard-A', label='Google.te-IN-Standard-A', language=self.get_language('te-IN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.te-IN-Standard-B', label='Google.te-IN-Standard-B', language=self.get_language('te-IN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.th-TH-Standard-A', label='Google.th-TH-Standard-A', language=self.get_language('th-TH'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.tr-TR-Standard-A', label='Google.tr-TR-Standard-A', language=self.get_language('tr-TR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.tr-TR-Standard-B', label='Google.tr-TR-Standard-B', language=self.get_language('tr-TR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.tr-TR-Standard-C', label='Google.tr-TR-Standard-C', language=self.get_language('tr-TR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.tr-TR-Standard-D', label='Google.tr-TR-Standard-D', language=self.get_language('tr-TR'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.tr-TR-Standard-E', label='Google.tr-TR-Standard-E', language=self.get_language('tr-TR'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.tr-TR-Wavenet-A', label='Google.tr-TR-Wavenet-A', language=self.get_language('tr-TR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.tr-TR-Wavenet-B', label='Google.tr-TR-Wavenet-B', language=self.get_language('tr-TR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.tr-TR-Wavenet-C', label='Google.tr-TR-Wavenet-C', language=self.get_language('tr-TR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.tr-TR-Wavenet-D', label='Google.tr-TR-Wavenet-D', language=self.get_language('tr-TR'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.tr-TR-Wavenet-E', label='Google.tr-TR-Wavenet-E', language=self.get_language('tr-TR'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Filiz', label='Polly.Filiz', language=self.get_language('tr-TR'), speech_type='Standard',
                  gender='Female'),
            Voice(name='Google.uk-UA-Standard-A', label='Google.uk-UA-Standard-A', language=self.get_language('uk-UA'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.uk-UA-Wavenet-A', label='Google.uk-UA-Wavenet-A', language=self.get_language('uk-UA'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.vi-VN-Standard-A', label='Google.vi-VN-Standard-A', language=self.get_language('vi-VN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.vi-VN-Standard-B', label='Google.vi-VN-Standard-B', language=self.get_language('vi-VN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.vi-VN-Standard-C', label='Google.vi-VN-Standard-C', language=self.get_language('vi-VN'),
                  speech_type='Standard', gender='Female'),
            Voice(name='Google.vi-VN-Standard-D', label='Google.vi-VN-Standard-D', language=self.get_language('vi-VN'),
                  speech_type='Standard', gender='Male'),
            Voice(name='Google.vi-VN-Wavenet-A', label='Google.vi-VN-Wavenet-A', language=self.get_language('vi-VN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.vi-VN-Wavenet-B', label='Google.vi-VN-Wavenet-B', language=self.get_language('vi-VN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Google.vi-VN-Wavenet-C', label='Google.vi-VN-Wavenet-C', language=self.get_language('vi-VN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.vi-VN-Wavenet-D', label='Google.vi-VN-Wavenet-D', language=self.get_language('vi-VN'),
                  speech_type='Premium', gender='Male'),
            Voice(name='Polly.Hiujin-Neural', label='Polly.Hiujin-Neural', language=self.get_language('yue-CN'),
                  speech_type='Premium', gender='Female'),
            Voice(name='Google.yue-HK-Standard-A', label='Google.yue-HK-Standard-A',
                  language=self.get_language('yue-HK'), speech_type='Standard', gender='Female'),
            Voice(name='Google.yue-HK-Standard-B', label='Google.yue-HK-Standard-B',
                  language=self.get_language('yue-HK'), speech_type='Standard', gender='Male'),
            Voice(name='Google.yue-HK-Standard-C', label='Google.yue-HK-Standard-C',
                  language=self.get_language('yue-HK'), speech_type='Standard', gender='Female'),
            Voice(name='Google.yue-HK-Standard-D', label='Google.yue-HK-Standard-D',
                  language=self.get_language('yue-HK'), speech_type='Standard', gender='Male')
        ]
