# Generated by Django 4.2.7 on 2024-02-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_setup',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='draft', max_length=30),
        ),
    ]
