# Generated by Django 4.2.7 on 2024-02-05 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('user', '0002_remove_user_is_setup_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=30)),
                ('token', models.CharField(max_length=100)),
                ('is_single_use', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(default='primary', max_length=20)),
                ('status', models.CharField(default='pending-verification', max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userphone_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userphone_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(default='primary', max_length=20)),
                ('status', models.CharField(default='pending-verification', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useremail_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useremail_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(default='primary', max_length=20)),
                ('status', models.CharField(default='active', max_length=30)),
                ('house_number', models.CharField(max_length=10)),
                ('street_pre_directional', models.CharField(max_length=2, null=True)),
                ('street_name', models.CharField(max_length=50)),
                ('street_suffix', models.CharField(max_length=4, null=True)),
                ('street_post_directional', models.CharField(max_length=2, null=True)),
                ('unit_type', models.CharField(max_length=4, null=True)),
                ('unit_number', models.CharField(max_length=10, null=True)),
                ('line1', models.CharField(max_length=100, null=True)),
                ('line2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useraddress_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useraddress_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_name='user_addresses', to='user.useraddress'),
        ),
        migrations.AddField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(related_name='user_emails', to='user.useremail'),
        ),
        migrations.AddField(
            model_name='user',
            name='phones',
            field=models.ManyToManyField(related_name='user_phones', to='user.userphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.ManyToManyField(related_name='user_tokens', to='user.usertoken'),
        ),
    ]
