---
name: Deployment Testing
on:
  workflow_dispatch:
  push:
    branches:
      - main-off
jobs:
  deployment_test_ubuntu_linux_2204:
    runs-on: [self-hosted, linux, x64]
    environment: testing
    concurrency:
      group: deployment_test_ubuntu_linux_2204
      cancel-in-progress: true
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3